# Default values for byzer-notebook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: nb-byzer-notebook
engine: bz-byzer-lang-service
enginePort: 9003
domain: cluster.local


service:
  type: ClusterIP
  port: 9002

resources:
  memory: 1G
  cpu: 1
  memoryOverheadFactor: 0.1   

notebook:
  port: 9002
## Byzer-Notebook private key to encrypt and decrypt password.
  security.key: 6173646661736466e4bda0e8bf983161
## Byzer-lang will use this directory to save user's data. Please
## make sure /byzer is accessible in Byzer-lang 
  user.home: /work/users
  url: "http://{{- .Values.name -}}.{{- .Release.Namespace -}}.svc.{{- .Values.domain -}}:{{- .Values.service.port -}}"
## Byzer-lang URL
  mlsql.engine-url: "http://{{- .Values.engine -}}.{{- .Release.Namespace -}}.svc.{{- .Values.domain -}}:{{- .Values.enginePort -}}"
  mlsql.engine-backup-url: "http://{{- .Values.engine -}}.{{- .Release.Namespace -}}.svc.{{- .Values.domain -}}:{{- .Values.enginePort -}}"
  mlsql.skipAuth: true
  mlsql.fetchType: take
  mlsql.access_token: mlsql
  mlsql.auth-client: streaming.dsl.auth.client.DefaultConsoleClient
  job.output-size: 50
  job.history.max-size: 100
  job.history.max-time: 30

## If true, please deploy DolphinScheduler
  scheduler.enable: false
  scheduler.scheduler-url: "http://dolphin-api.flag-qa:12345/dolphinscheduler"
## Auth token of dolphin user byzerRobot
  scheduler.auth-token: xxx
## The notebook callback for scheduler, the url uses K8S internal DNS.
  scheduler.callback-url: "http://{{- .Values.name -}}.{{- .Release.Namespace -}}.svc.{{- .Values.domain -}}:{{- .Values.service.port -}}/api/v1/notebook/scheduler/callback"
## Byzer-Notebook's database config
  database.port: 3306
  database.name: notebook  
  database.ip: "127.0.0.1"
  database.username: "byzer"
  database.password: "byzer"


replicaCount: 1
minReadySeconds: 300

image:
  repository: byzer/byzer-notebook
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.2.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "byzer"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


## Ingress is enabled by default.
ingress:
  enabled: true
  className: "nginx"
  path: /
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 50m        
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  tls: []
  #  - secretName: chart-example-tls
  hosts:
  #      - chart-example.local



autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

