apiVersion: v1
kind: Namespace
metadata:
  name: byzer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: byzer
  namespace: byzer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: byzer-admin
rules:
- apiGroups: [""]
  resources: ["pods","deployments", "replicas", "secrets", "configmaps","services","ingresses"]
  verbs: ["*"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: byzer-role-binding
subjects:
- kind: ServiceAccount
  name: byzer
  namespace: byzer
roleRef:
  kind: ClusterRole
  name: byzer-admin
  apiGroup: rbac.authorization.k8s.io   