annotations:
  category: Data/AI
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.4.0-SNAPSHOT
description: Byzer-lang is a low-code, open-sourced and distributed programming language
  for data pipeline, analytics and AI in cloud native way.
home: https://byzer.org/
icon: https://www.byzer.org/favicon.png
sources:
  - https://github.com/byzer-org/byzer-helm/tree/master/byzer-lang
keywords:
- sql-like-dsl
- bigdata
- machine-learning
- byzer-lang
name: byzer-lang
type: application
version: 0.1.6

dependencies:
  - name: common
    version: 2.2.2
    repository: https://charts.bitnami.com/bitnami

maintainers:
  - name: WilliamZhu
    email: allwefantasy@gmail.com
