# Default values for byzer-lang.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


## Kubenertes Cluster URL
clusterUrl: https://192.168.3.58:16443


## To use cloud storage, set fs.cloud.storage.enabled=true
## All fs.* go to core-site.xml

## Aliyun OSS Example
fs:
  cloud:
    storage:
      enabled: true
  oss.impl: org.apache.hadoop.fs.aliyun.oss.AliyunOSSFileSystem
  defaultFS: oss://xxxxxx
  oss.endpoint: oss-cn-hangzhou.aliyuncs.com
  oss.accessKeyId: xxxxx
  oss.accessKeySecret: xxxxx

## Azure Blob config  
#fs:
#  cloud:
#    storage:
#      enabled: true
#  defaultFS: wasb://<storage_account>@<container_name>.blob.core.chinacloudapi.cn/
#  AbstractFileSystem.wasb.impl: org.apache.hadoop.fs.azure.Wasb
#  wasb.impl: org.apache.hadoop.fs.azure.NativeAzureFileSystem
#  azure.rename.threads: 10
#  azure.delete.threads: 10
#  azure.account.key.flagk8sstorage.blob.core.chinacloudapi.cn: abcdef

## JuiceFS Example(Non-PVC)
# fs:
#   cloud:
#     storage:
#       enabled: true
#   jfs.impl: io.juicefs.JuiceFileSystem
#   AbstractFileSystem.jfs.impl: io.juicefs.JuiceFS
#   defaultFS: jfs://byjfs/
  
# juicefs:
#   name: byjfs
#   meta: mysql://xxxx:xxxx@(xxxxx:3306)/juicefs
#   cache-dir: /tmp/jfs
#   cache-size: 1024
#   access-log: /work/logs/juicefs.access.log
#   debug: true

## To use pvc
# pvc:
#   enabled: false
#   claimName: juicefs-pvc
#   mountPath: /byzer

## AWS S3 Example
# fs:
#   cloud:
#     storage:
#       enabled: true
#   defaultFS: s3a://xxxxxx
#   AbstractFileSystem.s3a.impl: org.apache.hadoop.fs.s3a.S3A
#   s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem    
#   s3a.endpoint: s3.ap-northeast-1.amazonaws.com
#   s3a.bucket.xxxx.access.key: xxxxx
#   s3a.bucket.xxxx.secret.key: xxxxx

## Azure Blob(abfs) Example
# fs:
#   cloud:
#     storage:
#       enabled: true
#   abfs.impl: org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem
#   defaultFS: abfs://xxxxxx
#   azure.account.auth.type.xxxxx.dfs.core.windows.net: SharedKey
#   fs.azure.account.key.xxxxx.dfs.core.windows.net: xxxxx  

## Huawei OBS Example
# fs:
#   cloud:
#     storage:
#       enabled: true
#   obs.impl: org.apache.hadoop.fs.obs.OBSFileSystem
#   AbstractFileSystem.obs.impl: org.apache.hadoop.fs.obs.OBSorg.apache.hadoop.fs.obs.OBS
#   defaultFS: obs://xxxxxx
#   obs.endpoint: obs.ap-southeast-3.myhuaweicloud.com
#   obs.access.key: xxxxx
#   obs.secret.key: xxxxx

## Tencent Cos Example
# fs:
#   cloud:
#     storage:
#       enabled: true
#   cosn.impl: org.apache.hadoop.fs.CosFileSystem
#   AbstractFileSystem.cosn.impl: org.apache.hadoop.fs.CosN
#   defaultFS: oss://xxxxxx
#   cosn.userinfo.secretId: xxxxx
#   cosn.userinfo.secretKey: xxxxx

## Byzer-lang Config
streaming:
  executor.login.driver: true
  datalake.path: /byzer/_delta
  enableHiveSupport: false
  plugin.clzznames: tech.mlsql.plugins.mllib.app.MLSQLMllib

## Byzer Spark Runtime Config
spark:
  driver.memory: 4g
  driver.cores: 2
  driver.maxResultSize: 1g  
  executor.memory: 1g
  executor.cores: 1
  executor.instances: 1
  driver.extraClassPath: local:///home/deploy/byzer-lang/plugin/mlsql-assert-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/plugin/mlsql-excel-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/plugin/mlsql-ext-ets-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/plugin/mlsql-shell-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/plugin/mlsql-mllib-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/main/byzer-lang-3.3.0-2.12-2.4.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/libs/juicefs-hadoop-1.0.0.jar:local:///home/deploy/byzer-lang/libs/byzer-objectstore-obs-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/libs/byzer-objectstore-blob-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/libs/byzer-objectstore-s3-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/libs/byzer-objectstore-oss-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/libs/byzer-objectstore-cos-3.3_2.12-0.1.0-SNAPSHOT.jar
  executor.extraClassPath: local:///home/deploy/byzer-lang/plugin/mlsql-assert-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/plugin/mlsql-excel-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/plugin/mlsql-ext-ets-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/plugin/mlsql-shell-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/plugin/mlsql-mllib-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/main/byzer-lang-3.3.0-2.12-2.4.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/libs/juicefs-hadoop-1.0.0.jar:local:///home/deploy/byzer-lang/libs/byzer-objectstore-obs-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/libs/byzer-objectstore-blob-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/libs/byzer-objectstore-s3-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/libs/byzer-objectstore-oss-3.3_2.12-0.1.0-SNAPSHOT.jar:local:///home/deploy/byzer-lang/libs/byzer-objectstore-cos-3.3_2.12-0.1.0-SNAPSHOT.jar
  hadoop.mapreduce.input.fileinputformat.list-status.num-threads: 10
  sql.cbo.enabled: true
  sql.joinReorder.enabled: true
  sql.planStats.enabled: true
  sql.starSchemaDetection: true
  sql.crossJoin.enabled: true
  sql.adaptive.enabled: true
  dynamicAllocation.enabled: false
  serializer: org.apache.spark.serializer.KryoSerializer
  kryoserializer.buffer.max: 1024m
  scheduler.mode: FAIR
  kubernetes.allocation.driver.readinessTimeout: 60s

byzer:
  mainJar: local:///home/deploy/byzer-lang/main/byzer-lang-3.3.0-2.12-2.4.0-SNAPSHOT.jar
# Hive config
# When streaming.enableHiveSupport true, Hive config is applied.
#hive:
#  hive.imetastoreclient.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
#  aws.region: us-west-2
#  aws.glue.cache.table.enable: true
#  aws.glue.cache.table.size: 1000
#  aws.glue.cache.table.ttl-mins: 30
#  aws.glue.cache.db.enable: true
#  aws.glue.cache.db.size: 1000
#  aws.glue.cache.db.ttl-mins: 30

## log4j2 config
# log4j2:
#   logger.executor.name: org.apache.spark.executor
#   logger.executor.level: warn

replicaCount: 1
minReadySeconds: 30

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 60

livenessProbe:
  initialDelaySeconds: 70
  periodSeconds: 300

image:
  repository: registry.cn-shanghai.aliyuncs.com/kyligence-byzer/byzer-lang-k8s-full
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.3.0-latest"
  imagePullSecrets: []

chart:
  nameOverride: ""
  fullnameOverride: ""

serviceAccount:
  annotations: {}
  name: byzer
  create: false

service:
  type: ClusterIP
  port: 9003

deployment:
  replicaCount: 1
  minReadySeconds: 30
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 100
    targetMemoryUtilizationPercentage: 100

pod:
  nodeSelector: { }
  affinity: {}
  tolerations: [ ]
  podSecurityContext: {}
  podAnnotations:
    name: byzer-lang
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 60
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 300

container:
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

## Byzer-lang ingress 
ingress:
  enabled: true
  className: "nginx"
  path: /byzer-lang(/|$)(.*)
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    # nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.50.1/8
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  tls: [ ]