apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "byzer-lang.fullname" . }}-configmap
data:
  hive-site-xml: |
    <configuration>
      {{- range $key, $value := .Values.hive }}
        <property>
          <name>{{- $key }}</name>
          <value>{{- $value }}</value>
        </property>
      {{- end }}
    </configuration>
  core-site-xml: |
    <configuration>
      {{- if .Values.fs.cloud.storage.enabled }}    
        {{- range $key, $value := .Values.fs }}
        <property>
          <name>fs.{{- $key }}</name>
          <value>{{- $value }}</value>
        </property>
        {{- end }}
        {{- range $key, $value := .Values.juicefs }}
        <property>
          <name>juicefs.{{- $key }}</name>
          <value>{{- $value }}</value>
        </property>
        {{- end }}
      {{- end }}
    </configuration>
  # There has to be "|-"
  log4j2-properties: |-    
    {{- range $key, $value := .Values.log4j2 }}
    {{ $key }}={{- $value }}  
    {{- end }}
  # Spark default configuration, read by spark-submit
  spark-defaults-conf: |-
    {{- range $key, $value := .Values.spark }}
    spark.{{- $key }} {{ $value }}
    {{- end }}
    spark.kubernetes.container.image.pullPolicy {{ .Values.image.pullPolicy }}
    spark.kubernetes.authenticate.driver.serviceAccountName {{ include "byzer-lang.serviceAccountName" . }}
    spark.kubernetes.container.image {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
    spark.kubernetes.namespace {{ .Release.Namespace }}
#  # Byzer config
  byzer-properties-override: |-
    {{- range $key, $value := .Values.streaming }}
    streaming.{{- $key }}={{ $value }}
    {{- end }}
    spark.master=k8s://{{- .Values.clusterUrl }}