name: Lint and Test Charts

on: [pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install bitnami repo
        run: helm repo  add bitnami https://charts.bitnami.com/bitnami

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: start minikube
        uses: medyagh/setup-minikube@latest
        id: minikube
        with:
          cache: true
          minikube-version: 1.22.0

      - name: Copy and edit values.yaml
        run: python -m pip install ruamel.yaml kubernetes && cd byzer-lang && python ./cp_write_values_yaml.py

      - name: Run byzer-lang-testing (install)
        run:  ct install --debug --chart-dirs ./byzer-lang --charts byzer-lang --helm-extra-args '--timeout 480s'
